In [15]:
#单层神经网络模拟
import numpy as np
x = np.array([[0,0],[1,0],[0,1],[1,1]])
z_reg = np.array([-0.2,-0.05,-0.05,0.1])

In [16]:
def LinearR (x1,x2):
    w1,w2,b = 0.15,0.15,-0.2
    z = x1*w1 + x2*w2 + b
    return z

In [17]:
LinearR(x[:,0],x[:,1])

array([-0.2 , -0.05, -0.05,  0.1 ])

In [18]:
#单层分类神经网络模拟
x = np.array([[0,0],[1,0],[0,1],[1,1]])
y_and = np.array([0,0,0,1])

def sigmoid (z):
    return 1/(1+np.exp(-z))

def And_sigmoid (x1,x2):
    w1,w2,b = 0.15,0.15,-0.2
    z = x1*w1 + x2*w2 + b
    o = sigmoid(z)
    y = [int(x) for x in o >= 0.5]
    return o,y

In [19]:
And_sigmoid(x[:,0],x[:,1])

(array([0.450166  , 0.4875026 , 0.4875026 , 0.52497919]), [0, 0, 0, 1])

In [20]:
#单层分类神经网络模拟(2)
def AND (x1,x2):
    w1,w2,b = 0.15,0.15,-0.23
    z = x1*w1 + x2*w2 + b
    y = [int(x) for x in z >= 0]
    return y
AND(x[:,0],x[:,1])

[0, 0, 0, 1]

In [3]:
import numpy as np
z = np.array([1010,1000,900])
def softmax (z):

    c = max(z)
    exp_z = np.exp(z-c)
    sum_exp_z = np.sum(exp_z)
    o = exp_z/sum_exp_z
    return o
softmax(z)

array([9.99954602e-01, 4.53978687e-05, 1.68883521e-48])